package com.cableex.mall.persistence.crm.primitive;

import com.cableex.mall.domain.crm.primitive.CmallSearchKeywords;
import com.cableex.mall.domain.crm.primitive.CmallSearchKeywordsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CmallSearchKeywordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CMALL_SEARCH_KEYWORDS
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    int countByExample(CmallSearchKeywordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CMALL_SEARCH_KEYWORDS
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    int deleteByExample(CmallSearchKeywordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CMALL_SEARCH_KEYWORDS
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CMALL_SEARCH_KEYWORDS
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    int insert(CmallSearchKeywords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CMALL_SEARCH_KEYWORDS
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    int insertSelective(CmallSearchKeywords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CMALL_SEARCH_KEYWORDS
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    List<CmallSearchKeywords> selectByExample(CmallSearchKeywordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CMALL_SEARCH_KEYWORDS
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    CmallSearchKeywords selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CMALL_SEARCH_KEYWORDS
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    int updateByExampleSelective(@Param("record") CmallSearchKeywords record, @Param("example") CmallSearchKeywordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CMALL_SEARCH_KEYWORDS
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    int updateByExample(@Param("record") CmallSearchKeywords record, @Param("example") CmallSearchKeywordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CMALL_SEARCH_KEYWORDS
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    int updateByPrimaryKeySelective(CmallSearchKeywords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CMALL_SEARCH_KEYWORDS
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    int updateByPrimaryKey(CmallSearchKeywords record);
}