package com.cableex.mall.persistence.xmall.primitive;

import com.cableex.mall.domain.xmall.primitive.PrtCatgoryAttrFront;
import com.cableex.mall.domain.xmall.primitive.PrtCatgoryAttrFrontExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PrtCatgoryAttrFrontMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRT_CATGORY_ATTR_FRONT
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    int countByExample(PrtCatgoryAttrFrontExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRT_CATGORY_ATTR_FRONT
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    int deleteByExample(PrtCatgoryAttrFrontExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRT_CATGORY_ATTR_FRONT
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRT_CATGORY_ATTR_FRONT
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    int insert(PrtCatgoryAttrFront record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRT_CATGORY_ATTR_FRONT
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    int insertSelective(PrtCatgoryAttrFront record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRT_CATGORY_ATTR_FRONT
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    List<PrtCatgoryAttrFront> selectByExample(PrtCatgoryAttrFrontExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRT_CATGORY_ATTR_FRONT
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    PrtCatgoryAttrFront selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRT_CATGORY_ATTR_FRONT
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    int updateByExampleSelective(@Param("record") PrtCatgoryAttrFront record, @Param("example") PrtCatgoryAttrFrontExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRT_CATGORY_ATTR_FRONT
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    int updateByExample(@Param("record") PrtCatgoryAttrFront record, @Param("example") PrtCatgoryAttrFrontExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRT_CATGORY_ATTR_FRONT
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    int updateByPrimaryKeySelective(PrtCatgoryAttrFront record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRT_CATGORY_ATTR_FRONT
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    int updateByPrimaryKey(PrtCatgoryAttrFront record);
}