package com.cableex.mall.domain.xmall.primitive;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class PrtCatgoryAttrFront implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRT_CATGORY_ATTR_FRONT.ID
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRT_CATGORY_ATTR_FRONT.ATTR_NAME
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    private String attrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRT_CATGORY_ATTR_FRONT.CREATE_DATE
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRT_CATGORY_ATTR_FRONT.ATTR_SEQUENCE
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    private BigDecimal attrSequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRT_CATGORY_ATTR_FRONT.CAT_ID
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    private String catId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRT_CATGORY_ATTR_FRONT.ATTR_CODE
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    private String attrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRT_CATGORY_ATTR_FRONT.IS_SHOW
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    private String isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_PRT_CATGORY_ATTR_FRONT
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRT_CATGORY_ATTR_FRONT.ID
     *
     * @return the value of T_PRT_CATGORY_ATTR_FRONT.ID
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRT_CATGORY_ATTR_FRONT.ID
     *
     * @param id the value for T_PRT_CATGORY_ATTR_FRONT.ID
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRT_CATGORY_ATTR_FRONT.ATTR_NAME
     *
     * @return the value of T_PRT_CATGORY_ATTR_FRONT.ATTR_NAME
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    public String getAttrName() {
        return attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRT_CATGORY_ATTR_FRONT.ATTR_NAME
     *
     * @param attrName the value for T_PRT_CATGORY_ATTR_FRONT.ATTR_NAME
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    public void setAttrName(String attrName) {
        this.attrName = attrName == null ? null : attrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRT_CATGORY_ATTR_FRONT.CREATE_DATE
     *
     * @return the value of T_PRT_CATGORY_ATTR_FRONT.CREATE_DATE
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRT_CATGORY_ATTR_FRONT.CREATE_DATE
     *
     * @param createDate the value for T_PRT_CATGORY_ATTR_FRONT.CREATE_DATE
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRT_CATGORY_ATTR_FRONT.ATTR_SEQUENCE
     *
     * @return the value of T_PRT_CATGORY_ATTR_FRONT.ATTR_SEQUENCE
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    public BigDecimal getAttrSequence() {
        return attrSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRT_CATGORY_ATTR_FRONT.ATTR_SEQUENCE
     *
     * @param attrSequence the value for T_PRT_CATGORY_ATTR_FRONT.ATTR_SEQUENCE
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    public void setAttrSequence(BigDecimal attrSequence) {
        this.attrSequence = attrSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRT_CATGORY_ATTR_FRONT.CAT_ID
     *
     * @return the value of T_PRT_CATGORY_ATTR_FRONT.CAT_ID
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    public String getCatId() {
        return catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRT_CATGORY_ATTR_FRONT.CAT_ID
     *
     * @param catId the value for T_PRT_CATGORY_ATTR_FRONT.CAT_ID
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    public void setCatId(String catId) {
        this.catId = catId == null ? null : catId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRT_CATGORY_ATTR_FRONT.ATTR_CODE
     *
     * @return the value of T_PRT_CATGORY_ATTR_FRONT.ATTR_CODE
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    public String getAttrCode() {
        return attrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRT_CATGORY_ATTR_FRONT.ATTR_CODE
     *
     * @param attrCode the value for T_PRT_CATGORY_ATTR_FRONT.ATTR_CODE
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    public void setAttrCode(String attrCode) {
        this.attrCode = attrCode == null ? null : attrCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRT_CATGORY_ATTR_FRONT.IS_SHOW
     *
     * @return the value of T_PRT_CATGORY_ATTR_FRONT.IS_SHOW
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    public String getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRT_CATGORY_ATTR_FRONT.IS_SHOW
     *
     * @param isShow the value for T_PRT_CATGORY_ATTR_FRONT.IS_SHOW
     *
     * @mbggenerated Sun May 17 15:17:22 CST 2015
     */
    public void setIsShow(String isShow) {
        this.isShow = isShow == null ? null : isShow.trim();
    }
}