package com.cableex.mall.domain.xmall.primitive;

import com.cableex.core.util.page.Page;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class VFrontCatgoryAttr4SolrExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table V_FRONT_CATGORY_ATTR_4SOLR
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table V_FRONT_CATGORY_ATTR_4SOLR
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table V_FRONT_CATGORY_ATTR_4SOLR
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table V_FRONT_CATGORY_ATTR_4SOLR
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    protected Page page;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_FRONT_CATGORY_ATTR_4SOLR
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    public VFrontCatgoryAttr4SolrExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_FRONT_CATGORY_ATTR_4SOLR
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_FRONT_CATGORY_ATTR_4SOLR
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_FRONT_CATGORY_ATTR_4SOLR
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_FRONT_CATGORY_ATTR_4SOLR
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_FRONT_CATGORY_ATTR_4SOLR
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_FRONT_CATGORY_ATTR_4SOLR
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_FRONT_CATGORY_ATTR_4SOLR
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_FRONT_CATGORY_ATTR_4SOLR
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_FRONT_CATGORY_ATTR_4SOLR
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_FRONT_CATGORY_ATTR_4SOLR
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_FRONT_CATGORY_ATTR_4SOLR
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    public void setPage(Page page) {
        this.page=page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_FRONT_CATGORY_ATTR_4SOLR
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    public Page getPage() {
        return page;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table V_FRONT_CATGORY_ATTR_4SOLR
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andChannelIdIsNull() {
            addCriterion("CHANNEL_ID is null");
            return (Criteria) this;
        }

        public Criteria andChannelIdIsNotNull() {
            addCriterion("CHANNEL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andChannelIdEqualTo(String value) {
            addCriterion("CHANNEL_ID =", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotEqualTo(String value) {
            addCriterion("CHANNEL_ID <>", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdGreaterThan(String value) {
            addCriterion("CHANNEL_ID >", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdGreaterThanOrEqualTo(String value) {
            addCriterion("CHANNEL_ID >=", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLessThan(String value) {
            addCriterion("CHANNEL_ID <", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLessThanOrEqualTo(String value) {
            addCriterion("CHANNEL_ID <=", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLike(String value) {
            addCriterion("CHANNEL_ID like", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotLike(String value) {
            addCriterion("CHANNEL_ID not like", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdIn(List<String> values) {
            addCriterion("CHANNEL_ID in", values, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotIn(List<String> values) {
            addCriterion("CHANNEL_ID not in", values, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdBetween(String value1, String value2) {
            addCriterion("CHANNEL_ID between", value1, value2, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotBetween(String value1, String value2) {
            addCriterion("CHANNEL_ID not between", value1, value2, "channelId");
            return (Criteria) this;
        }

        public Criteria andLev3CatNameIsNull() {
            addCriterion("LEV3_CAT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andLev3CatNameIsNotNull() {
            addCriterion("LEV3_CAT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andLev3CatNameEqualTo(String value) {
            addCriterion("LEV3_CAT_NAME =", value, "lev3CatName");
            return (Criteria) this;
        }

        public Criteria andLev3CatNameNotEqualTo(String value) {
            addCriterion("LEV3_CAT_NAME <>", value, "lev3CatName");
            return (Criteria) this;
        }

        public Criteria andLev3CatNameGreaterThan(String value) {
            addCriterion("LEV3_CAT_NAME >", value, "lev3CatName");
            return (Criteria) this;
        }

        public Criteria andLev3CatNameGreaterThanOrEqualTo(String value) {
            addCriterion("LEV3_CAT_NAME >=", value, "lev3CatName");
            return (Criteria) this;
        }

        public Criteria andLev3CatNameLessThan(String value) {
            addCriterion("LEV3_CAT_NAME <", value, "lev3CatName");
            return (Criteria) this;
        }

        public Criteria andLev3CatNameLessThanOrEqualTo(String value) {
            addCriterion("LEV3_CAT_NAME <=", value, "lev3CatName");
            return (Criteria) this;
        }

        public Criteria andLev3CatNameLike(String value) {
            addCriterion("LEV3_CAT_NAME like", value, "lev3CatName");
            return (Criteria) this;
        }

        public Criteria andLev3CatNameNotLike(String value) {
            addCriterion("LEV3_CAT_NAME not like", value, "lev3CatName");
            return (Criteria) this;
        }

        public Criteria andLev3CatNameIn(List<String> values) {
            addCriterion("LEV3_CAT_NAME in", values, "lev3CatName");
            return (Criteria) this;
        }

        public Criteria andLev3CatNameNotIn(List<String> values) {
            addCriterion("LEV3_CAT_NAME not in", values, "lev3CatName");
            return (Criteria) this;
        }

        public Criteria andLev3CatNameBetween(String value1, String value2) {
            addCriterion("LEV3_CAT_NAME between", value1, value2, "lev3CatName");
            return (Criteria) this;
        }

        public Criteria andLev3CatNameNotBetween(String value1, String value2) {
            addCriterion("LEV3_CAT_NAME not between", value1, value2, "lev3CatName");
            return (Criteria) this;
        }

        public Criteria andAttrNameIsNull() {
            addCriterion("ATTR_NAME is null");
            return (Criteria) this;
        }

        public Criteria andAttrNameIsNotNull() {
            addCriterion("ATTR_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andAttrNameEqualTo(String value) {
            addCriterion("ATTR_NAME =", value, "attrName");
            return (Criteria) this;
        }

        public Criteria andAttrNameNotEqualTo(String value) {
            addCriterion("ATTR_NAME <>", value, "attrName");
            return (Criteria) this;
        }

        public Criteria andAttrNameGreaterThan(String value) {
            addCriterion("ATTR_NAME >", value, "attrName");
            return (Criteria) this;
        }

        public Criteria andAttrNameGreaterThanOrEqualTo(String value) {
            addCriterion("ATTR_NAME >=", value, "attrName");
            return (Criteria) this;
        }

        public Criteria andAttrNameLessThan(String value) {
            addCriterion("ATTR_NAME <", value, "attrName");
            return (Criteria) this;
        }

        public Criteria andAttrNameLessThanOrEqualTo(String value) {
            addCriterion("ATTR_NAME <=", value, "attrName");
            return (Criteria) this;
        }

        public Criteria andAttrNameLike(String value) {
            addCriterion("ATTR_NAME like", value, "attrName");
            return (Criteria) this;
        }

        public Criteria andAttrNameNotLike(String value) {
            addCriterion("ATTR_NAME not like", value, "attrName");
            return (Criteria) this;
        }

        public Criteria andAttrNameIn(List<String> values) {
            addCriterion("ATTR_NAME in", values, "attrName");
            return (Criteria) this;
        }

        public Criteria andAttrNameNotIn(List<String> values) {
            addCriterion("ATTR_NAME not in", values, "attrName");
            return (Criteria) this;
        }

        public Criteria andAttrNameBetween(String value1, String value2) {
            addCriterion("ATTR_NAME between", value1, value2, "attrName");
            return (Criteria) this;
        }

        public Criteria andAttrNameNotBetween(String value1, String value2) {
            addCriterion("ATTR_NAME not between", value1, value2, "attrName");
            return (Criteria) this;
        }

        public Criteria andAttrSequenceIsNull() {
            addCriterion("ATTR_SEQUENCE is null");
            return (Criteria) this;
        }

        public Criteria andAttrSequenceIsNotNull() {
            addCriterion("ATTR_SEQUENCE is not null");
            return (Criteria) this;
        }

        public Criteria andAttrSequenceEqualTo(BigDecimal value) {
            addCriterion("ATTR_SEQUENCE =", value, "attrSequence");
            return (Criteria) this;
        }

        public Criteria andAttrSequenceNotEqualTo(BigDecimal value) {
            addCriterion("ATTR_SEQUENCE <>", value, "attrSequence");
            return (Criteria) this;
        }

        public Criteria andAttrSequenceGreaterThan(BigDecimal value) {
            addCriterion("ATTR_SEQUENCE >", value, "attrSequence");
            return (Criteria) this;
        }

        public Criteria andAttrSequenceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ATTR_SEQUENCE >=", value, "attrSequence");
            return (Criteria) this;
        }

        public Criteria andAttrSequenceLessThan(BigDecimal value) {
            addCriterion("ATTR_SEQUENCE <", value, "attrSequence");
            return (Criteria) this;
        }

        public Criteria andAttrSequenceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ATTR_SEQUENCE <=", value, "attrSequence");
            return (Criteria) this;
        }

        public Criteria andAttrSequenceIn(List<BigDecimal> values) {
            addCriterion("ATTR_SEQUENCE in", values, "attrSequence");
            return (Criteria) this;
        }

        public Criteria andAttrSequenceNotIn(List<BigDecimal> values) {
            addCriterion("ATTR_SEQUENCE not in", values, "attrSequence");
            return (Criteria) this;
        }

        public Criteria andAttrSequenceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ATTR_SEQUENCE between", value1, value2, "attrSequence");
            return (Criteria) this;
        }

        public Criteria andAttrSequenceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ATTR_SEQUENCE not between", value1, value2, "attrSequence");
            return (Criteria) this;
        }

        public Criteria andAttrCodeIsNull() {
            addCriterion("ATTR_CODE is null");
            return (Criteria) this;
        }

        public Criteria andAttrCodeIsNotNull() {
            addCriterion("ATTR_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andAttrCodeEqualTo(String value) {
            addCriterion("ATTR_CODE =", value, "attrCode");
            return (Criteria) this;
        }

        public Criteria andAttrCodeNotEqualTo(String value) {
            addCriterion("ATTR_CODE <>", value, "attrCode");
            return (Criteria) this;
        }

        public Criteria andAttrCodeGreaterThan(String value) {
            addCriterion("ATTR_CODE >", value, "attrCode");
            return (Criteria) this;
        }

        public Criteria andAttrCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ATTR_CODE >=", value, "attrCode");
            return (Criteria) this;
        }

        public Criteria andAttrCodeLessThan(String value) {
            addCriterion("ATTR_CODE <", value, "attrCode");
            return (Criteria) this;
        }

        public Criteria andAttrCodeLessThanOrEqualTo(String value) {
            addCriterion("ATTR_CODE <=", value, "attrCode");
            return (Criteria) this;
        }

        public Criteria andAttrCodeLike(String value) {
            addCriterion("ATTR_CODE like", value, "attrCode");
            return (Criteria) this;
        }

        public Criteria andAttrCodeNotLike(String value) {
            addCriterion("ATTR_CODE not like", value, "attrCode");
            return (Criteria) this;
        }

        public Criteria andAttrCodeIn(List<String> values) {
            addCriterion("ATTR_CODE in", values, "attrCode");
            return (Criteria) this;
        }

        public Criteria andAttrCodeNotIn(List<String> values) {
            addCriterion("ATTR_CODE not in", values, "attrCode");
            return (Criteria) this;
        }

        public Criteria andAttrCodeBetween(String value1, String value2) {
            addCriterion("ATTR_CODE between", value1, value2, "attrCode");
            return (Criteria) this;
        }

        public Criteria andAttrCodeNotBetween(String value1, String value2) {
            addCriterion("ATTR_CODE not between", value1, value2, "attrCode");
            return (Criteria) this;
        }

        public Criteria andIsShowIsNull() {
            addCriterion("IS_SHOW is null");
            return (Criteria) this;
        }

        public Criteria andIsShowIsNotNull() {
            addCriterion("IS_SHOW is not null");
            return (Criteria) this;
        }

        public Criteria andIsShowEqualTo(String value) {
            addCriterion("IS_SHOW =", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowNotEqualTo(String value) {
            addCriterion("IS_SHOW <>", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowGreaterThan(String value) {
            addCriterion("IS_SHOW >", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowGreaterThanOrEqualTo(String value) {
            addCriterion("IS_SHOW >=", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowLessThan(String value) {
            addCriterion("IS_SHOW <", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowLessThanOrEqualTo(String value) {
            addCriterion("IS_SHOW <=", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowLike(String value) {
            addCriterion("IS_SHOW like", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowNotLike(String value) {
            addCriterion("IS_SHOW not like", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowIn(List<String> values) {
            addCriterion("IS_SHOW in", values, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowNotIn(List<String> values) {
            addCriterion("IS_SHOW not in", values, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowBetween(String value1, String value2) {
            addCriterion("IS_SHOW between", value1, value2, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowNotBetween(String value1, String value2) {
            addCriterion("IS_SHOW not between", value1, value2, "isShow");
            return (Criteria) this;
        }

        public Criteria andChannelIdLikeInsensitive(String value) {
            addCriterion("upper(CHANNEL_ID) like", value.toUpperCase(), "channelId");
            return (Criteria) this;
        }

        public Criteria andLev3CatNameLikeInsensitive(String value) {
            addCriterion("upper(LEV3_CAT_NAME) like", value.toUpperCase(), "lev3CatName");
            return (Criteria) this;
        }

        public Criteria andAttrNameLikeInsensitive(String value) {
            addCriterion("upper(ATTR_NAME) like", value.toUpperCase(), "attrName");
            return (Criteria) this;
        }

        public Criteria andAttrCodeLikeInsensitive(String value) {
            addCriterion("upper(ATTR_CODE) like", value.toUpperCase(), "attrCode");
            return (Criteria) this;
        }

        public Criteria andIsShowLikeInsensitive(String value) {
            addCriterion("upper(IS_SHOW) like", value.toUpperCase(), "isShow");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table V_FRONT_CATGORY_ATTR_4SOLR
     *
     * @mbggenerated do_not_delete_during_merge Mon May 25 13:56:26 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table V_FRONT_CATGORY_ATTR_4SOLR
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}