package com.cableex.mall.domain.xmall.primitive;

import java.io.Serializable;
import java.math.BigDecimal;

public class VFrontCatgoryAttr4Solr implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_FRONT_CATGORY_ATTR_4SOLR.CHANNEL_ID
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    private String channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_FRONT_CATGORY_ATTR_4SOLR.LEV3_CAT_NAME
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    private String lev3CatName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_FRONT_CATGORY_ATTR_4SOLR.ATTR_NAME
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    private String attrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_FRONT_CATGORY_ATTR_4SOLR.ATTR_SEQUENCE
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    private BigDecimal attrSequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_FRONT_CATGORY_ATTR_4SOLR.ATTR_CODE
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    private String attrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_FRONT_CATGORY_ATTR_4SOLR.IS_SHOW
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    private String isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table V_FRONT_CATGORY_ATTR_4SOLR
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_FRONT_CATGORY_ATTR_4SOLR.CHANNEL_ID
     *
     * @return the value of V_FRONT_CATGORY_ATTR_4SOLR.CHANNEL_ID
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_FRONT_CATGORY_ATTR_4SOLR.CHANNEL_ID
     *
     * @param channelId the value for V_FRONT_CATGORY_ATTR_4SOLR.CHANNEL_ID
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_FRONT_CATGORY_ATTR_4SOLR.LEV3_CAT_NAME
     *
     * @return the value of V_FRONT_CATGORY_ATTR_4SOLR.LEV3_CAT_NAME
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    public String getLev3CatName() {
        return lev3CatName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_FRONT_CATGORY_ATTR_4SOLR.LEV3_CAT_NAME
     *
     * @param lev3CatName the value for V_FRONT_CATGORY_ATTR_4SOLR.LEV3_CAT_NAME
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    public void setLev3CatName(String lev3CatName) {
        this.lev3CatName = lev3CatName == null ? null : lev3CatName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_FRONT_CATGORY_ATTR_4SOLR.ATTR_NAME
     *
     * @return the value of V_FRONT_CATGORY_ATTR_4SOLR.ATTR_NAME
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    public String getAttrName() {
        return attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_FRONT_CATGORY_ATTR_4SOLR.ATTR_NAME
     *
     * @param attrName the value for V_FRONT_CATGORY_ATTR_4SOLR.ATTR_NAME
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    public void setAttrName(String attrName) {
        this.attrName = attrName == null ? null : attrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_FRONT_CATGORY_ATTR_4SOLR.ATTR_SEQUENCE
     *
     * @return the value of V_FRONT_CATGORY_ATTR_4SOLR.ATTR_SEQUENCE
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    public BigDecimal getAttrSequence() {
        return attrSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_FRONT_CATGORY_ATTR_4SOLR.ATTR_SEQUENCE
     *
     * @param attrSequence the value for V_FRONT_CATGORY_ATTR_4SOLR.ATTR_SEQUENCE
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    public void setAttrSequence(BigDecimal attrSequence) {
        this.attrSequence = attrSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_FRONT_CATGORY_ATTR_4SOLR.ATTR_CODE
     *
     * @return the value of V_FRONT_CATGORY_ATTR_4SOLR.ATTR_CODE
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    public String getAttrCode() {
        return attrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_FRONT_CATGORY_ATTR_4SOLR.ATTR_CODE
     *
     * @param attrCode the value for V_FRONT_CATGORY_ATTR_4SOLR.ATTR_CODE
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    public void setAttrCode(String attrCode) {
        this.attrCode = attrCode == null ? null : attrCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_FRONT_CATGORY_ATTR_4SOLR.IS_SHOW
     *
     * @return the value of V_FRONT_CATGORY_ATTR_4SOLR.IS_SHOW
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    public String getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_FRONT_CATGORY_ATTR_4SOLR.IS_SHOW
     *
     * @param isShow the value for V_FRONT_CATGORY_ATTR_4SOLR.IS_SHOW
     *
     * @mbggenerated Mon May 25 13:56:26 CST 2015
     */
    public void setIsShow(String isShow) {
        this.isShow = isShow == null ? null : isShow.trim();
    }
}