package com.cableex.mall.domain.crm.primitive;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class CmallSearchKeywords implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CMALL_SEARCH_KEYWORDS.ID
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CMALL_SEARCH_KEYWORDS.SEARCH_TIME
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    private Date searchTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CMALL_SEARCH_KEYWORDS.SEARCH_KEYWORDS
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    private String searchKeywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CMALL_SEARCH_KEYWORDS.SOURCE
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CMALL_SEARCH_KEYWORDS.TYPE
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CMALL_SEARCH_KEYWORDS.MEMBER_ID
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    private BigDecimal memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CMALL_SEARCH_KEYWORDS.SESSION_ID
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    private String sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CMALL_SEARCH_KEYWORDS.IMEI
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    private String imei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CMALL_SEARCH_KEYWORDS.IS_DELETE
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CMALL_SEARCH_KEYWORDS.SEARCH_IP
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    private String searchIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_CMALL_SEARCH_KEYWORDS
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CMALL_SEARCH_KEYWORDS.ID
     *
     * @return the value of T_CMALL_SEARCH_KEYWORDS.ID
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CMALL_SEARCH_KEYWORDS.ID
     *
     * @param id the value for T_CMALL_SEARCH_KEYWORDS.ID
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CMALL_SEARCH_KEYWORDS.SEARCH_TIME
     *
     * @return the value of T_CMALL_SEARCH_KEYWORDS.SEARCH_TIME
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    public Date getSearchTime() {
        return searchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CMALL_SEARCH_KEYWORDS.SEARCH_TIME
     *
     * @param searchTime the value for T_CMALL_SEARCH_KEYWORDS.SEARCH_TIME
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    public void setSearchTime(Date searchTime) {
        this.searchTime = searchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CMALL_SEARCH_KEYWORDS.SEARCH_KEYWORDS
     *
     * @return the value of T_CMALL_SEARCH_KEYWORDS.SEARCH_KEYWORDS
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    public String getSearchKeywords() {
        return searchKeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CMALL_SEARCH_KEYWORDS.SEARCH_KEYWORDS
     *
     * @param searchKeywords the value for T_CMALL_SEARCH_KEYWORDS.SEARCH_KEYWORDS
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    public void setSearchKeywords(String searchKeywords) {
        this.searchKeywords = searchKeywords == null ? null : searchKeywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CMALL_SEARCH_KEYWORDS.SOURCE
     *
     * @return the value of T_CMALL_SEARCH_KEYWORDS.SOURCE
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CMALL_SEARCH_KEYWORDS.SOURCE
     *
     * @param source the value for T_CMALL_SEARCH_KEYWORDS.SOURCE
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CMALL_SEARCH_KEYWORDS.TYPE
     *
     * @return the value of T_CMALL_SEARCH_KEYWORDS.TYPE
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CMALL_SEARCH_KEYWORDS.TYPE
     *
     * @param type the value for T_CMALL_SEARCH_KEYWORDS.TYPE
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CMALL_SEARCH_KEYWORDS.MEMBER_ID
     *
     * @return the value of T_CMALL_SEARCH_KEYWORDS.MEMBER_ID
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    public BigDecimal getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CMALL_SEARCH_KEYWORDS.MEMBER_ID
     *
     * @param memberId the value for T_CMALL_SEARCH_KEYWORDS.MEMBER_ID
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    public void setMemberId(BigDecimal memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CMALL_SEARCH_KEYWORDS.SESSION_ID
     *
     * @return the value of T_CMALL_SEARCH_KEYWORDS.SESSION_ID
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CMALL_SEARCH_KEYWORDS.SESSION_ID
     *
     * @param sessionId the value for T_CMALL_SEARCH_KEYWORDS.SESSION_ID
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId == null ? null : sessionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CMALL_SEARCH_KEYWORDS.IMEI
     *
     * @return the value of T_CMALL_SEARCH_KEYWORDS.IMEI
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CMALL_SEARCH_KEYWORDS.IMEI
     *
     * @param imei the value for T_CMALL_SEARCH_KEYWORDS.IMEI
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    public void setImei(String imei) {
        this.imei = imei == null ? null : imei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CMALL_SEARCH_KEYWORDS.IS_DELETE
     *
     * @return the value of T_CMALL_SEARCH_KEYWORDS.IS_DELETE
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CMALL_SEARCH_KEYWORDS.IS_DELETE
     *
     * @param isDelete the value for T_CMALL_SEARCH_KEYWORDS.IS_DELETE
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CMALL_SEARCH_KEYWORDS.SEARCH_IP
     *
     * @return the value of T_CMALL_SEARCH_KEYWORDS.SEARCH_IP
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    public String getSearchIp() {
        return searchIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CMALL_SEARCH_KEYWORDS.SEARCH_IP
     *
     * @param searchIp the value for T_CMALL_SEARCH_KEYWORDS.SEARCH_IP
     *
     * @mbggenerated Tue Nov 07 14:24:14 CST 2017
     */
    public void setSearchIp(String searchIp) {
        this.searchIp = searchIp == null ? null : searchIp.trim();
    }
}